name: citmatel_strawberry_tools
description: Tools that have in commons all CITMATEL's 'strawberry' projects

publish_to: "none"

version: 0.0.1-SNAPSHOT.20220104

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Architecture & Management
  get: ^4.5.1

  #Animations
  flutter_spinkit: ^5.1.0

  #Utils
  vibration: ^1.7.4-nullsafety.0
  #Audio
  assets_audio_player: ^3.0.3+9

  #Make Conffeti Effect
  animated_background: ^2.0.0
  confetti: ^0.6.0

  #Animated Letters
  animated_text_kit: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - packages/citmatel_strawberry_tools/assets/audios/keyboard_correct.wav
    - packages/citmatel_strawberry_tools/assets/audios/keyboard_error.mp3
    - packages/citmatel_strawberry_tools/assets/audios/lose_sad_trombone.wav
    - packages/citmatel_strawberry_tools/assets/audios/win_applause.wav
    - packages/citmatel_strawberry_tools/assets/icons/baby_boy.png
    - packages/citmatel_strawberry_tools/assets/icons/baby_girl.png
