name: citmatel_strawberry_tools
description: Tools that have in commons all CITMATEL's 'strawberry' projects

publish_to: 'none'

version: 0.0.1-SNAPSHOT.20220104

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Utils
  vibration: ^1.7.4-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

